/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConectarBD;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Javir
 */
public class PanelConectar extends javax.swing.JPanel {

    static private Connection conexion=null;
    /**
     * Creates new form PanelConectar
     */
    public PanelConectar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioLabel = new javax.swing.JLabel();
        contraseñaLabel = new javax.swing.JLabel();
        confirmContraseñaLabel = new javax.swing.JLabel();
        contraseñaField = new javax.swing.JPasswordField();
        confirmContraseñaField = new javax.swing.JPasswordField();
        usuarioField = new javax.swing.JTextField();
        btConectar = new javax.swing.JButton();

        usuarioLabel.setText("Usuario:");

        contraseñaLabel.setText("Contraseña: ");

        confirmContraseñaLabel.setText("Confime contraseña: ");

        btConectar.setText("Conectar");
        btConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contraseñaLabel)
                    .addComponent(usuarioLabel)
                    .addComponent(confirmContraseñaLabel))
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(confirmContraseñaField, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(contraseñaField)
                    .addComponent(usuarioField))
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btConectar)
                .addGap(218, 218, 218))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usuarioLabel)
                    .addComponent(usuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contraseñaLabel)
                            .addComponent(contraseñaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(confirmContraseñaLabel))
                    .addComponent(confirmContraseñaField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btConectar)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConectarActionPerformed
        
        char[] arr_contraseña;
        String contraseña;
        
        if(comprobarContraseña()){
            
            ConectarBD con=new ConectarBD();
            arr_contraseña=contraseñaField.getPassword();
            contraseña=String.valueOf(arr_contraseña);
            System.out.println("Usuario: "+usuarioField.getText()+" Contraseña: "+contraseña);
            try {
                conexion=con.conectar(usuarioField.getText(),contraseña);
                Principal.setConexion(conexion);
                setMensajeExito("Conectado a la base de datos con éxito");
            } catch (SQLException ex) {
                setMensajeError("El usuario o la contraseña no son válidos");
            }
        }else{
            setMensajeError("Las contraseñas introducidas no coinciden");
        }
    }//GEN-LAST:event_btConectarActionPerformed

    
    public Connection getConexion(){
        return conexion;
    }
    
    public void setMensajeError(String mensaje){
        JOptionPane.showMessageDialog(this,mensaje,"Error al conectarse a la base de datos",JOptionPane.ERROR_MESSAGE);
    }
    
    
    public void setMensajeExito(String mensaje){
        JOptionPane.showMessageDialog(this,mensaje,"Conectado",JOptionPane.INFORMATION_MESSAGE);
    }
    
    
    
    @SuppressWarnings("empty-statement")
    private boolean comprobarContraseña(){
        
        char[] arr_contraseña=contraseñaField.getPassword();
        char[] arr_contraseñaConfirm=confirmContraseñaField.getPassword();
        
        String contraseña=Arrays.toString(arr_contraseña);
        String contraseñaConfirm=Arrays.toString(arr_contraseñaConfirm);
        
        return contraseña.equals(contraseñaConfirm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConectar;
    private javax.swing.JPasswordField confirmContraseñaField;
    private javax.swing.JLabel confirmContraseñaLabel;
    private javax.swing.JPasswordField contraseñaField;
    private javax.swing.JLabel contraseñaLabel;
    private javax.swing.JTextField usuarioField;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
